#!/bin/bash

go get -v -u golang.org/x/tools/cmd/...
go get -v -u github.com/golang/lint/golint
go get -v -u github.com/kisielk/errcheck
go get -v -u github.com/cespare/prettybench
go get -v -u github.com/rogpeppe/godef
go get -v -u github.com/nsf/gocode
go get -v -u github.com/kisielk/godepgraph
go get -v -u github.com/pkg/profile
go get -v -u github.com/jstemmer/gotags
go get -v -u github.com/smartystreets/goconvey
go get -v -u github.com/mattn/gom
go get -v -u github.com/laher/goxc
go get -v -u github.com/motemen/gore
go get -v -u github.com/mattn/goreman
go get -v -u github.com/adjust/go-wrk
go get -v -u github.com/mholt/caddy
go get -v -u github.com/caddyserver/builds
go get -v -u github.com/alecthomas/gometalinter
go get -v -u github.com/kardianos/govendor
go get -v -u github.com/campoy/embedmd
go get -v -u github.com/y0ssar1an/q
go get -v -u github.com/joewalnes/websocketd
go get -v -u github.com/benas/gossed
go get -v -u github.com/davecheney/httpstat
go get -v -u github.com/guillaumebreton/gone
go get -v -u github.com/rakyll/hey
go get -v -u github.com/derekparker/delve/cmd/dlv
go get -v -u github.com/aarzilli/gdlv
go get -v -u github.com/davecgh/go-spew/spew
go get -v -u github.com/golang/dep/cmd/dep
go get -u -v github.com/iawia002/annie
go get -u -v github.com/claudiodangelis/qr-filetransfer
